[package]
name = "lambubu"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = { version = "6.1.0", optional = true }
pest = "2.8.6"
pest_derive = "2.8.6"
thiserror = "2.0.18"

[features]
default = ["cache"]
dashmap = ["dep:dashmap"]
cache = ["dashmap"]
