[package]
name = "lambubu_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
lambubu = { path = "../lambubu" }
proc-macro2 = "1.0.106"
quote = "1.0.44"
syn = "2.0.117"
